- name: "install node exporter."
  unarchive:
<<<<<<< HEAD
    src: https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz
=======
    src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
>>>>>>> 592dcbf006932edb87665227966be2c36ddb622b
    dest: /tmp
    remote_src: yes

- name: "move binary to /usr/local/bin."
  become: true
  copy:
<<<<<<< HEAD
    src: /tmp/node_exporter-1.4.0.linux-amd64/node_exporter
=======
    src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
>>>>>>> 592dcbf006932edb87665227966be2c36ddb622b
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: '0777'
    
- name: "add node exporter configuration."
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: "enable node_exporter service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes